In [3]:
import numpy as np

arr = np.arange(0,10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [6]:
yut = np.linspace(1,20,50)
print(yut)

[ 1.          1.3877551   1.7755102   2.16326531  2.55102041  2.93877551
  3.32653061  3.71428571  4.10204082  4.48979592  4.87755102  5.26530612
  5.65306122  6.04081633  6.42857143  6.81632653  7.20408163  7.59183673
  7.97959184  8.36734694  8.75510204  9.14285714  9.53061224  9.91836735
 10.30612245 10.69387755 11.08163265 11.46938776 11.85714286 12.24489796
 12.63265306 13.02040816 13.40816327 13.79591837 14.18367347 14.57142857
 14.95918367 15.34693878 15.73469388 16.12244898 16.51020408 16.89795918
 17.28571429 17.67346939 18.06122449 18.44897959 18.83673469 19.2244898
 19.6122449  20.        ]


In [12]:

print(arr1 *2)

[ 0  2  4  6  8 10 12 14 16 18]


In [14]:
suv  = np.ones((2,4),dtype = int)
print(suv)

[[1 1 1 1]
 [1 1 1 1]]


In [27]:
vcn = np.random.rand(3,3,)
print(vcn)

[[0.5163     0.4219167  0.40191593]
 [0.1767558  0.75862403 0.5473244 ]
 [0.63956996 0.21882965 0.10433421]]


In [21]:
nyc = np.random.randint(1,100,15).reshape(3,5)
print(nyc)

[[33 89 48 96 30]
 [66  9 27 83 88]
 [42 44 82 52 27]]


In [24]:
vbn = np.random.random_sample(8).reshape(4,2)
print(vbn)

[[0.94104819 0.11772341]
 [0.0150669  0.63079967]
 [0.5920102  0.07355249]
 [0.39169479 0.56653741]]
